/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import javax.swing.JOptionPane;
import static proyecto1.MenuPrincipal.ListaDeCuentas;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Luisda
 */
public class DepositoMonetario extends javax.swing.JFrame {
    
    static DateTimeFormatter fecha2 = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");

    public static String[][] ParaComboBox2() {
        int contador = 0;
        for (int i = 1; i < ListaDeCuentas.length; i++) {
            if (ListaDeCuentas[i] == null) {
                break;
            }
            contador++;
        }
        String[][] TextoEnCombo = new String[2][contador];
        for (int i = 1; i < contador + 1; i++) {
            TextoEnCombo[0][i - 1] = "ID: " + ListaDeCuentas[i].IDcuenta + " | Dueño: " + ListaDeCuentas[i].Dueno.Nombre + " " + ListaDeCuentas[i].Dueno.Apellido;
            TextoEnCombo[1][i - 1] = String.valueOf(ListaDeCuentas[i].IDcuenta);

        }
        return TextoEnCombo;
    }

    /**
     * Creates new form DepositoMonetario
     */
    public DepositoMonetario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CuentaCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextoMonto = new javax.swing.JTextField();
        BotonAceptar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deposito Monetario");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Deposito Monetario");

        CuentaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(ParaComboBox2()[0]));
        CuentaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Elija una cuenta...");

        jLabel3.setText("Elija el monto...");

        TextoMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoMontoActionPerformed(evt);
            }
        });

        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addComponent(BotonCancelar))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CuentaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoMonto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CuentaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAceptar)
                    .addComponent(BotonCancelar))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CuentaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaComboActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        // TODO add your handling code here:
        if (Integer.valueOf(TextoMonto.getText()) < 0 || Integer.valueOf(TextoMonto.getText()) == 0) {
            JOptionPane.showMessageDialog(null, "La cantidad que ha introducido no es valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            MenuPrincipal.ListaDeCuentas[CuentaCombo.getSelectedIndex() + 1].Saldo = MenuPrincipal.ListaDeCuentas[CuentaCombo.getSelectedIndex() + 1].Saldo + Integer.valueOf(TextoMonto.getText());
            MenuPrincipal.ListaDeCuentas[CuentaCombo.getSelectedIndex() + 1].SaldoCuenta();
            JOptionPane.showMessageDialog(null, "Deposito realizado con éxito", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            for (int i = 0; i < 25; i++) {
            if (MenuPrincipal.Historial[CuentaCombo.getSelectedIndex() + 1][0][i] == null) {
                
                MenuPrincipal.Historial[CuentaCombo.getSelectedIndex() + 1][0][i] = String.valueOf(MenuPrincipal.IDHistorial);
                MenuPrincipal.IDHistorial++;
                MenuPrincipal.Historial[CuentaCombo.getSelectedIndex() + 1][1][i] = fecha2.format(LocalDateTime.now());;
                MenuPrincipal.Historial[CuentaCombo.getSelectedIndex() + 1][2][i] = "Deposito";
                MenuPrincipal.Historial[CuentaCombo.getSelectedIndex() + 1][3][i] = "0";
                MenuPrincipal.Historial[CuentaCombo.getSelectedIndex() + 1][4][i] = TextoMonto.getText();
                MenuPrincipal.Historial[CuentaCombo.getSelectedIndex() + 1][5][i] = String.valueOf(MenuPrincipal.ListaDeCuentas[CuentaCombo.getSelectedIndex() + 1].Saldo);
                
                break;
            }
        }
            dispose();
        }

        


    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void TextoMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoMontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositoMonetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositoMonetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositoMonetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositoMonetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositoMonetario().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JComboBox<String> CuentaCombo;
    private javax.swing.JTextField TextoMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
