/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import javax.swing.JOptionPane;
import static proyecto1.Transferencia.ParaComboBox3;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Luisda
 */
public class PagoDeServicios extends javax.swing.JFrame {
    static DateTimeFormatter fecha = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");

    /**
     * Creates new form PagoDeServicios
     */
    public PagoDeServicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboCuentas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboServicio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TextoDebitar = new javax.swing.JTextField();
        BotonAceptar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago de Servicios");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pago de Servicios");

        ComboCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(ParaComboBox3()[0]));
        ComboCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCuentasActionPerformed(evt);
            }
        });

        jLabel2.setText("Cuenta a debitar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tipo de servicio");

        ComboServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luz Eléctrica", "Agua", "Servicio Telefónico" }));
        ComboServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboServicioActionPerformed(evt);
            }
        });

        jLabel4.setText("Monto a debitar");

        TextoDebitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDebitarActionPerformed(evt);
            }
        });

        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboCuentas, 0, 185, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextoDebitar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonCancelar))
                            .addComponent(ComboServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoDebitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAceptar)
                    .addComponent(BotonCancelar))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoDebitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDebitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDebitarActionPerformed

    private void ComboCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCuentasActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        // TODO add your handling code here:

        if (Integer.parseInt(TextoDebitar.getText()) < 0 || Integer.parseInt(TextoDebitar.getText()) == 0) {
            JOptionPane.showMessageDialog(null, "El monto introducido no es valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (Integer.parseInt(TextoDebitar.getText()) > MenuPrincipal.ListaDeCuentas[ComboCuentas.getSelectedIndex() + 1].Saldo) {
            JOptionPane.showMessageDialog(null, "La cuenta no tiene suficiente saldo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            MenuPrincipal.ListaDeCuentas[ComboCuentas.getSelectedIndex() + 1].Saldo = MenuPrincipal.ListaDeCuentas[ComboCuentas.getSelectedIndex() + 1].Saldo - Integer.parseInt(TextoDebitar.getText());
            JOptionPane.showMessageDialog(null, "Pago de servicio realizado con éxito", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(MenuPrincipal.ListaDeCuentas[ComboCuentas.getSelectedIndex() + 1].Saldo);
            for (int i = 0; i < 25; i++) {
                if (MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][0][i] == null) {

                    MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][0][i] = String.valueOf(MenuPrincipal.IDHistorial);
                    MenuPrincipal.IDHistorial++;
                    MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][1][i] = fecha.format(LocalDateTime.now());

                    switch (ComboServicio.getSelectedIndex()) {
                        case 0:
                            MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][2][i] = "Pago de Servicio - Luz Electrica";
                            break;
                        case 1:
                            MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][2][i] = "Pago de Servicio - Agua";
                            break;
                        case 2:
                            MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][2][i] = "Pago de Servicio - Servicio Telefonico";
                            break;

                    }

                    MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][3][i] = TextoDebitar.getText();
                    MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][4][i] = "0";
                    MenuPrincipal.Historial[ComboCuentas.getSelectedIndex() + 1][5][i] = String.valueOf(MenuPrincipal.ListaDeCuentas[ComboCuentas.getSelectedIndex() + 1].Saldo);

                    break;
                }
            }
            dispose();
        }


    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void ComboServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoDeServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JComboBox<String> ComboCuentas;
    private javax.swing.JComboBox<String> ComboServicio;
    private javax.swing.JTextField TextoDebitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
